"""empty message

Revision ID: 350cdd64c2ba
Revises: d03fa6393704
Create Date: 2025-03-16 10:33:58.806833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350cdd64c2ba'
down_revision = 'd03fa6393704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
